"""token -> jti

Revision ID: c6d283646162
Revises: 811d2b5d7f3e
Create Date: 2024-07-31 13:25:32.962255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d283646162'
down_revision: Union[str, None] = '811d2b5d7f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.String(), nullable=False))
    op.drop_index('ix_refresh_tokens_token', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.drop_column('refresh_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token', 'refresh_tokens', ['token'], unique=True)
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
