[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Gleb B. <baburin899@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.1"
pydantic-settings = "^2.3.4"
asyncpg = "^0.29.0"
psycopg = "^3.2.1"
python-jose = "^3.3.0"
python-dotenv = "^1.0.1"
httpx = "^0.27.0"
black = "^24.4.2"
pytest-asyncio = "^0.23.8"
alembic = "^1.13.2"
passlib = "^1.7.4"
bs4 = "^0.0.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-asyncio = "^0.23.8"
httpx = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
